#!/bin/bash

set -euo pipefail

if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" ]; then
  dpkg-divert \
    --package libasound2-plugins-a52 \
    --remove \
    --rename \
    --divert /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_a52.so.orig \
    /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_a52.so
fi
